import { IKanji } from '../kanji';

export const firstWords: IKanji[] = [
    {
        francais: 'La personne',
        kanji: '人',
        hiragana: 'ひと',
        katakana: 'ヒト',
        romaji: 'hito',
    },
    {
        francais: 'L\'homme',
        kanji: '男',
        hiragana: 'おとこ',
        katakana: 'オトコ',
        romaji: 'otoko',
    },
    {
        francais: 'La femme',
        kanji: '女',
        hiragana: 'おんな',
        katakana: 'オンナ',
        romaji: 'onna',
    },
    {
        francais: 'L\'enfant',
        kanji: '子',
        hiragana: 'こ',
        katakana: 'コ',
        romaji: 'ko',
    },
    {
        francais: 'Le soleil',
        kanji: '日',
        hiragana: 'ひ',
        katakana: 'ヒ',
        romaji: 'hi',
    },
    {
        francais: 'La lune',
        kanji: '月',
        hiragana: 'つき',
        katakana: 'ツキ',
        romaji: 'tsuki',
    },
    {
        francais: 'Le temps',
        kanji: '時',
        hiragana: 'とき',
        katakana: 'トキ',
        romaji: 'toki',
    },
    {
        francais: 'L\'eau',
        kanji: '水',
        hiragana: 'みず',
        katakana: 'ミズ',
        romaji: 'mizu',
    },
    {
        francais: 'Le feu',
        kanji: '火',
        hiragana: 'ひ',
        katakana: 'ヒ',
        romaji: 'hi',
    },
    {
        francais: 'La terre',
        kanji: '土',
        hiragana: 'つち',
        katakana: 'ツチ',
        romaji: 'tsuchi',
    },
    {
        francais: 'Le vent',
        kanji: '風',
        hiragana: 'かぜ',
        katakana: 'カゼ',
        romaji: 'kaze',
    },
    {
        francais: 'le ciel',
        kanji: '空',
        hiragana: 'そら',
        katakana: 'ソラ',
        romaji: 'sora',
    },
    {
        francais: 'La montagne',
        kanji: '山',
        hiragana: 'やま',
        katakana: 'ヤマ',
        romaji: 'yama',
    },
    {
        francais: 'La rivière',
        kanji: '川',
        hiragana: 'かわ',
        katakana: 'カワ',
        romaji: 'kawa',
    },
    {
        francais: 'L\'arbre',
        kanji: '木',
        hiragana: 'き',
        katakana: 'キ',
        romaji: 'ki',
    },
    {
        francais: 'La fleur',
        kanji: '花',
        hiragana: 'はな',
        katakana: 'ハナ',
        romaji: 'hana',
    },
    {
        francais: 'La pluie',
        kanji: '雨',
        hiragana: 'あめ',
        katakana: 'アメ',
        romaji: 'ame',
    },
    {
        francais: 'La neige',
        kanji: '雪',
        hiragana: 'ゆき',
        katakana: 'ユキ',
        romaji: 'yuki',
    },
    {
        francais: 'L\'argent',
        kanji: '金',
        hiragana: 'かね',
        katakana: 'カネ',
        romaji: 'kane',
    },
    {
        francais: 'Le sabre',
        kanji: '刀',
        hiragana: 'かたな',
        katakana: 'カタナ',
        romaji: 'katana',
    },
];
